import React from 'react';
import { useFarm } from '../context/FarmContext';
import type { FeedType } from '../context/FarmContext';

export const Dashboard: React.FC = () => {
  const { batches, eggCollections, sales, expenses, getFeedStock, currentUser, pendingSubmissions } = useFarm();
  const isAdmin = currentUser?.role === 'Admin';

  // 1. KPI Calculations
  const activeBirds = batches
    .filter(b => b.status === 'Active')
    .reduce((sum, b) => sum + b.currentQuantity, 0);

  const totalFeedStock = (['Starter', 'Grower', 'Finisher', 'Layer Mash'] as FeedType[])
    .reduce((sum, type) => sum + getFeedStock(type), 0);

  const latestEggCollection = eggCollections[0]; 
  const todayEggs = latestEggCollection ? latestEggCollection.netQty : 0;

  const totalSales = sales.reduce((sum, s) => sum + s.totalAmount, 0);
  const totalExpenses = expenses.reduce((sum, e) => sum + e.amount, 0);
  const netProfit = totalSales - totalExpenses;

  // Format Helper
  const formatCurrency = (amount: number) => {
    const formatted = Math.abs(amount).toLocaleString(undefined, { maximumFractionDigits: 0 });
    return amount < 0 ? `-Rs ${formatted}` : `Rs ${formatted}`;
  };



  // ==========================================
  // SVG CHART 1: EGG COLLECTION TREND (Line)
  // ==========================================
  const eggTrendData = [...eggCollections].reverse().slice(-7); // Last 7 days
  const maxEggs = Math.max(...eggTrendData.map(d => d.netQty), 1000);
  const minEggs = Math.min(...eggTrendData.map(d => d.netQty), 500);
  
  // Calculate SVG coordinates for line chart
  const width = 500;
  const height = 150;
  const padding = 25;
  const chartWidth = width - padding * 2;
  const chartHeight = height - padding * 2;

  const points = eggTrendData.map((d, index) => {
    const x = padding + (index / (eggTrendData.length - 1 || 1)) * chartWidth;
    // Normalize Y between min and max with margin
    const yRange = maxEggs - minEggs || 100;
    const yNormalized = (d.netQty - minEggs) / yRange;
    const y = padding + chartHeight - yNormalized * chartHeight;
    return { x, y, date: d.date, qty: d.netQty };
  });

  const pathD = points.length > 0 
    ? `M ${points[0].x} ${points[0].y} ` + points.slice(1).map(p => `L ${p.x} ${p.y}`).join(' ') 
    : '';

  const areaD = points.length > 0
    ? `${pathD} L ${points[points.length - 1].x} ${height - padding} L ${points[0].x} ${height - padding} Z`
    : '';

  // ==========================================
  // SVG CHART 2: FEED INVENTORY (Bars)
  // ==========================================
  const feedTypes: FeedType[] = ['Starter', 'Grower', 'Finisher', 'Layer Mash'];
  const feedStocks = feedTypes.map(type => ({
    type,
    qty: getFeedStock(type)
  }));
  const maxFeed = Math.max(...feedStocks.map(f => f.qty), 1200);

  // ==========================================
  // RECENT ACTIVITIES (Last 5 log items)
  // ==========================================
  const recentActivities: { id: string; text: string; date: string; type: string }[] = [];

  batches.forEach(b => {
    b.mortalityLogs.forEach(m => {
      recentActivities.push({
        id: m.id,
        text: `Log: ${m.quantity} bird mortality in Batch ${b.id} (${m.reason})`,
        date: m.date,
        type: 'mortality'
      });
    });
  });

  if (isAdmin) {
    sales.slice(0, 3).forEach(s => {
      recentActivities.push({
        id: s.id,
        text: `Sale: ${s.quantity.toLocaleString()} ${s.type === 'Bird' ? 'birds' : 'eggs'} to ${s.customerName}`,
        date: s.date,
        type: 'sale'
      });
    });

    expenses.filter(e => !e.isAutoGenerated).slice(0, 3).forEach(e => {
      recentActivities.push({
        id: e.id,
        text: `Expense: Registered Rs ${e.amount} for ${e.category} (${e.description})`,
        date: e.date,
        type: 'expense'
      });
    });
  }

  // Sort activities by date descending
  recentActivities.sort((a, b) => b.date.localeCompare(a.date));
  const activeLogs = recentActivities.slice(0, 5);

  return (
    <div className="dashboard-page animate-fade-in">
      {/* 1. KPIs */}
      <div className="grid-cols-4 kpi-container">
        <div className="glass-card kpi-card border-emerald">
          <div className="kpi-icon">🐤</div>
          <div className="kpi-data">
            <span className="kpi-label">Active Birds</span>
            <h3 className="kpi-value">{activeBirds.toLocaleString()}</h3>
            <span className="kpi-subtext">Across layer & broiler batches</span>
          </div>
        </div>

        <div className="glass-card kpi-card border-amber">
          <div className="kpi-icon">🌾</div>
          <div className="kpi-data">
            <span className="kpi-label">Feed in Stock</span>
            <h3 className="kpi-value">{totalFeedStock.toLocaleString()} kg</h3>
            <span className="kpi-subtext">Automatic consumption deduction</span>
          </div>
        </div>

        <div className="glass-card kpi-card border-cyan">
          <div className="kpi-icon">🥚</div>
          <div className="kpi-data">
            <span className="kpi-label">Egg Yield (Today)</span>
            <h3 className="kpi-value">{todayEggs.toLocaleString()}</h3>
            <span className="kpi-subtext">Usable eggs after damage logs</span>
          </div>
        </div>

        {isAdmin && (
          <div className="glass-card kpi-card border-indigo">
            <div className="kpi-icon">💹</div>
            <div className="kpi-data">
              <span className="kpi-label">Month Profit</span>
              <h3 className={`kpi-value ${netProfit >= 0 ? 'color-emerald' : 'color-rose'}`}>
                {formatCurrency(netProfit)}
              </h3>
              <span className="kpi-subtext">Total Sales vs Total Expenses</span>
            </div>
          </div>
        )}
      </div>

      {/* 2. Charts */}
      <div className="grid-cols-2 chart-card-container">
        {/* Egg production line chart */}
        <div className="glass-card">
          <div className="chart-header">
            <h4>Egg Production Trend (Last 7 Logs)</h4>
            <span className="chart-subtitle">Daily usable collections</span>
          </div>
          {eggTrendData.length < 2 ? (
            <div className="chart-empty-state">Not enough data to render trend line.</div>
          ) : (
            <div className="svg-chart-container">
              <svg viewBox={`0 0 ${width} ${height}`} width="100%" height="100%">
                {/* Grid Lines */}
                <line x1={padding} y1={padding} x2={width - padding} y2={padding} className="chart-grid-line" />
                <line x1={padding} y1={padding + chartHeight / 2} x2={width - padding} y2={padding + chartHeight / 2} className="chart-grid-line" />
                <line x1={padding} y1={height - padding} x2={width - padding} y2={height - padding} className="chart-grid-line" />
                
                {/* Gradient area */}
                <defs>
                  <linearGradient id="eggGlow" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="var(--color-cyan)" stopOpacity="0.3"/>
                    <stop offset="100%" stopColor="var(--color-cyan)" stopOpacity="0.0"/>
                  </linearGradient>
                </defs>
                <path d={areaD} fill="url(#eggGlow)" />

                {/* Line */}
                <path d={pathD} className="chart-line" stroke="var(--color-cyan)" />

                {/* Dots & Labels */}
                {points.map((p, i) => (
                  <g key={i}>
                    <circle cx={p.x} cy={p.y} r="4" fill="#ffffff" stroke="var(--color-cyan)" strokeWidth="2" />
                    <text x={p.x} y={p.y - 10} textAnchor="middle" fill="var(--text-primary)" fontSize="8" fontWeight="600">
                      {p.qty}
                    </text>
                    <text x={p.x} y={height - padding + 15} textAnchor="middle" fill="var(--text-muted)" fontSize="8">
                      {p.date.substring(5)}
                    </text>
                  </g>
                ))}
              </svg>
            </div>
          )}
        </div>

        {/* Feed levels bar chart */}
        <div className="glass-card">
          <div className="chart-header">
            <h4>Feed Inventory Levels (kg)</h4>
            <span className="chart-subtitle">Low stock warning under 300kg</span>
          </div>
          <div className="svg-chart-container">
            <svg viewBox="0 0 500 150" width="100%" height="100%">
              {/* Grid Lines */}
              <line x1="40" y1="20" x2="480" y2="20" className="chart-grid-line" />
              <line x1="40" y1="70" x2="480" y2="70" className="chart-grid-line" />
              <line x1="40" y1="120" x2="480" y2="120" className="chart-grid-line" />

              {/* Threshold line at 300kg */}
              {(() => {
                const threshY = 120 - (300 / maxFeed) * 100;
                return (
                  <line x1="40" y1={threshY} x2="480" y2={threshY} stroke="var(--color-rose)" strokeWidth="1" strokeDasharray="3" opacity="0.6" />
                );
              })()}

              {/* Bars */}
              {feedStocks.map((f, i) => {
                const barWidth = 50;
                const barSpacing = 70;
                const x = 60 + i * (barWidth + barSpacing);
                const barHeight = (f.qty / maxFeed) * 100;
                const y = 120 - barHeight;
                const isLow = f.qty < 300;

                return (
                  <g key={i}>
                    <rect
                      x={x}
                      y={y}
                      width={barWidth}
                      height={barHeight}
                      rx="4"
                      className="chart-bar"
                      fill={isLow ? 'var(--color-rose)' : 'var(--color-emerald)'}
                      opacity={isLow ? '0.75' : '0.65'}
                    />
                    <text x={x + barWidth / 2} y={y - 8} textAnchor="middle" fill="var(--text-primary)" fontSize="9" fontWeight="600">
                      {Math.round(f.qty)}k
                    </text>
                    <text x={x + barWidth / 2} y="135" textAnchor="middle" fill="var(--text-secondary)" fontSize="9">
                      {f.type.split(' ')[0]}
                    </text>
                  </g>
                );
              })}
            </svg>
          </div>
        </div>
      </div>

      {/* Employee Submissions & Approval Status */}
      {(() => {
        const userSubs = isAdmin 
          ? pendingSubmissions.filter(s => s.status === 'Pending')
          : pendingSubmissions.filter(s => s.submittedBy.toLowerCase() === (currentUser?.username || '').toLowerCase());
        
        if (userSubs.length === 0) return null;

        return (
          <div className="glass-card" style={{ border: '1px solid rgba(245, 158, 11, 0.35)', background: 'rgba(245, 158, 11, 0.03)' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '0.75rem' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem' }}>
                <span style={{ fontSize: '1.3rem' }}>⏳</span>
                <div>
                  <h4 style={{ margin: 0, color: 'var(--color-amber)' }}>
                    {isAdmin ? 'Farm Submissions Requiring Your Approval' : 'My Recent Submissions & Approval Status'}
                  </h4>
                  <p style={{ margin: '0.15rem 0 0 0', fontSize: '0.78rem', color: 'var(--text-muted)' }}>
                    {isAdmin 
                      ? `${userSubs.length} employee record(s) pending review in Employee Management.`
                      : 'Records logged by you stay pending until reviewed and approved by an administrator.'}
                  </p>
                </div>
              </div>
              <span className="badge badge-amber">{userSubs.filter(s => s.status === 'Pending').length} Pending</span>
            </div>

            <div className="table-wrapper" style={{ maxHeight: '200px', overflowY: 'auto' }}>
              <table>
                <thead>
                  <tr>
                    <th>Type</th>
                    <th>Date / Batch</th>
                    <th>Submission Summary</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {userSubs.slice(0, 5).map(sub => {
                    let desc = '';
                    if (sub.type === 'EggCollection') desc = `${sub.data.collectedQty} collected · ${sub.data.netQty} usable net`;
                    else if (sub.type === 'Mortality') desc = `${sub.data.quantity} birds lost (Reason: ${sub.data.reason})`;
                    else if (sub.type === 'FeedConsumption') desc = `${sub.data.quantityKg} kg ${sub.data.feedType} fed`;
                    else if (sub.type === 'FeedPurchase') desc = `${sub.data.quantityKg} kg ${sub.data.feedType} from ${sub.data.vendor}`;
                    else if (sub.type === 'VaccineSchedule') desc = `${sub.data.vaccineName}`;
                    else if (sub.type === 'VaccineStatusUpdate') desc = `Mark ${sub.data.vaccineName} as ${sub.data.status}`;
                    else if (sub.type === 'MedicalRecord') desc = `${sub.data.disease} (${sub.data.medicine})`;
                    else if (sub.type === 'BirdBatch') desc = `Batch ${sub.data.id} (${sub.data.initialQuantity} birds)`;

                    return (
                      <tr key={sub.id}>
                        <td>
                          <span className="role-badge employee" style={{ fontSize: '0.75rem', padding: '0.15rem 0.4rem' }}>
                            {sub.type}
                          </span>
                        </td>
                        <td>{sub.data.date || sub.data.scheduledDate || sub.data.arrivalDate || '—'} {sub.data.batchId ? `(Batch ${sub.data.batchId})` : ''}</td>
                        <td style={{ fontSize: '0.82rem' }}>{desc}</td>
                        <td>
                          <span className={`badge ${sub.status === 'Pending' ? 'badge-amber' : sub.status === 'Approved' ? 'badge-emerald' : 'badge-rose'}`}>
                            {sub.status === 'Pending' ? '⏳ Pending Review' : sub.status === 'Approved' ? '✅ Approved' : '❌ Rejected'}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        );
      })()}

      {/* 3. Bottom Row: Quick Tasks & Logs */}
      <div className="grid-cols-2 activity-row-container">
        {/* Real-time Activity Feed */}
        <div className="glass-card">
          <h4>Recent Operations Log</h4>
          <p className="chart-subtitle" style={{ marginBottom: '1rem' }}>Farm events tracked in real-time</p>
          <div className="activity-feed">
            {activeLogs.length === 0 ? (
              <div className="chart-empty-state">No operations logged yet.</div>
            ) : (
              activeLogs.map((act) => {
                let badgeClass = 'badge-cyan';
                let icon = '🔔';
                if (act.type === 'mortality') {
                  badgeClass = 'badge-rose';
                  icon = '⚠️';
                } else if (act.type === 'sale') {
                  badgeClass = 'badge-emerald';
                  icon = '📈';
                } else if (act.type === 'expense') {
                  badgeClass = 'badge-rose';
                  icon = '💸';
                }
                return (
                  <div key={act.id} className="activity-item">
                    <span className="activity-icon">{icon}</span>
                    <div className="activity-info">
                      <span className="activity-text">{act.text}</span>
                      <span className="activity-date">{act.date}</span>
                    </div>
                    <span className={`badge ${badgeClass} activity-badge`}>
                      {act.type}
                    </span>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Quick Instructions & Alert Checklist */}
        <div className="glass-card">
          <h4>System Alerts & Guidelines</h4>
          <p className="chart-subtitle" style={{ marginBottom: '1rem' }}>Automatic checks for maintenance</p>
          <div className="alerts-checklist">
            {feedStocks.some(f => f.qty < 300) && (
              <div className="system-alert alert-danger-custom">
                <span className="alert-icon">🚨</span>
                <div className="alert-text">
                  <h5>Low Feed Levels Detected</h5>
                  <p>
                    One or more feed types in your inventory are below the critical 300 kg limit. Make feed purchases as soon as possible.
                  </p>
                </div>
              </div>
            )}
            {batches.filter(b => b.status === 'Active' && b.currentQuantity < b.initialQuantity * 0.95).length > 0 && (
              <div className="system-alert alert-warning-custom">
                <span className="alert-icon">⚠️</span>
                <div className="alert-text">
                  <h5>High Batch Mortality Alert</h5>
                  <p>
                    A bird batch has experienced greater than 5% mortality. Check the vaccination schedule or treat with medical remedies.
                  </p>
                </div>
              </div>
            )}
            <div className="system-alert alert-info-custom">
              <span className="alert-icon">ℹ️</span>
              <div className="alert-text">
                <h5>Daily Egg Production Health Check</h5>
                <p>
                  Today's egg output is {todayEggs > 0 ? `${todayEggs} eggs` : 'pending logger'}. Layer batches require consistent morning schedules.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <style>{`
        .dashboard-page {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-lg);
        }

        .kpi-card {
          display: flex;
          align-items: center;
          gap: var(--spacing-lg);
          padding: var(--spacing-lg);
          border-left: 4px solid var(--border-color);
        }

        .kpi-card.border-emerald { border-left-color: var(--color-emerald); }
        .kpi-card.border-amber { border-left-color: var(--color-amber); }
        .kpi-card.border-cyan { border-left-color: var(--color-cyan); }
        .kpi-card.border-indigo { border-left-color: var(--color-indigo); }

        .kpi-icon {
          font-size: 2.25rem;
          width: 54px;
          height: 54px;
          border-radius: var(--radius-md);
          background: rgba(255, 255, 255, 0.03);
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .kpi-data {
          display: flex;
          flex-direction: column;
        }

        .kpi-label {
          font-size: 0.8rem;
          color: var(--text-secondary);
          text-transform: uppercase;
          letter-spacing: 0.05em;
          font-weight: 500;
        }

        .kpi-value {
          font-size: 1.5rem;
          font-weight: 700;
          color: var(--text-primary);
          margin: 0.15rem 0;
        }

        .kpi-subtext {
          font-size: 0.72rem;
          color: var(--text-muted);
        }

        .color-emerald { color: var(--color-emerald) !important; }
        .color-rose { color: var(--color-rose) !important; }

        .chart-header {
          display: flex;
          flex-direction: column;
          margin-bottom: var(--spacing-md);
        }

        .chart-subtitle {
          font-size: 0.8rem;
          color: var(--text-muted);
        }

        .chart-empty-state {
          height: 150px;
          display: flex;
          align-items: center;
          justify-content: center;
          color: var(--text-muted);
          font-size: 0.9rem;
          border: 1px dashed var(--border-color);
          border-radius: var(--radius-md);
          transition: border-color var(--transition-normal);
        }

        .activity-row-container {
          margin-top: var(--spacing-md);
        }

        .activity-feed {
          display: flex;
          flex-direction: column;
          gap: 0.75rem;
        }

        .activity-item {
          display: flex;
          align-items: center;
          padding: 0.65rem 0.85rem;
          background: var(--glass-button-bg);
          border: 1px solid var(--border-color);
          border-radius: var(--radius-md);
          gap: var(--spacing-md);
          transition: background-color var(--transition-normal), border-color var(--transition-normal);
        }

        .activity-icon {
          font-size: 1.15rem;
        }

        .activity-info {
          flex: 1;
          display: flex;
          flex-direction: column;
        }

        .activity-text {
          font-size: 0.85rem;
          font-weight: 500;
          color: var(--text-primary);
        }

        .activity-date {
          font-size: 0.72rem;
          color: var(--text-muted);
          margin-top: 2px;
        }

        .activity-badge {
          font-size: 0.65rem;
          padding: 0.1rem 0.4rem;
        }

        .alerts-checklist {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-md);
        }

        .system-alert {
          display: flex;
          padding: var(--spacing-md);
          border-radius: var(--radius-md);
          gap: var(--spacing-md);
          border: 1px solid transparent;
        }

        .system-alert h5 {
          font-size: 0.85rem;
          font-weight: 600;
          margin-bottom: 2px;
        }

        .system-alert p {
          font-size: 0.75rem;
          color: var(--text-secondary);
          line-height: 1.4;
        }

        .alert-icon {
          font-size: 1.25rem;
        }

        .alert-danger-custom {
          background: var(--alert-danger-bg);
          border-color: rgba(244, 63, 94, 0.15);
          color: var(--alert-danger-color);
          transition: background-color var(--transition-normal), color var(--transition-normal);
        }

        .alert-warning-custom {
          background: var(--alert-warning-bg);
          border-color: rgba(245, 158, 11, 0.15);
          color: var(--alert-warning-color);
          transition: background-color var(--transition-normal), color var(--transition-normal);
        }

        .alert-info-custom {
          background: var(--alert-info-bg);
          border-color: rgba(6, 182, 212, 0.15);
          color: var(--alert-info-color);
          transition: background-color var(--transition-normal), color var(--transition-normal);
        }

        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }

        .animate-fade-in {
          animation: fadeIn 0.3s ease-out;
        }
      `}</style>
    </div>
  );
};

