import React, { useState } from 'react';
import { useFarm } from '../context/FarmContext';
import type { ExpenseCategory } from '../context/FarmContext';
import { Modal } from '../components/Modal';

export const ExpenseMgmt: React.FC = () => {
  const { expenses, usersList, addExpense, deleteExpense, updateExpense } = useFarm();

  const [isAddModalOpen, setIsAddModalOpen] = useState(false);

  // Form Fields - Expense
  const [expCategory, setExpCategory] = useState<ExpenseCategory>('Electricity');
  const [expDate, setExpDate] = useState(new Date().toISOString().split('T')[0]);
  const [expDescription, setExpDescription] = useState('');
  const [expCost, setExpCost] = useState<number>(0);

  // Admin Verification for Editing Expense Records
  const [isAdminAuthModalOpen, setIsAdminAuthModalOpen] = useState(false);
  const [adminPasswordInput, setAdminPasswordInput] = useState('');
  const [adminAuthError, setAdminAuthError] = useState('');
  const [pendingEditExpense, setPendingEditExpense] = useState<any | null>(null);

  // Edit Expense States
  const [isEditModalOpen, setIsEditModalOpen] = useState(false);
  const [editingExpenseId, setEditingExpenseId] = useState('');
  const [editCategory, setEditCategory] = useState<ExpenseCategory>('Electricity');
  const [editDate, setEditDate] = useState('');
  const [editDescription, setEditDescription] = useState('');
  const [editCost, setEditCost] = useState<number>(0);
  const [editIsAutoGenerated, setEditIsAutoGenerated] = useState(false);

  const handleInitiateEdit = (e: any) => {
    setPendingEditExpense(e);
    setAdminPasswordInput('');
    setAdminAuthError('');
    setIsAdminAuthModalOpen(true);
  };

  const handleVerifyAdminAndExecute = async (ev?: React.FormEvent) => {
    if (ev) ev.preventDefault();
    if (!pendingEditExpense) return;

    const adminUser = usersList.find(u => u.role === 'Admin');
    const isPasswordCorrect = adminUser 
      ? adminUser.password === adminPasswordInput 
      : (adminPasswordInput === 'admin' || adminPasswordInput === '2001-02-23');

    if (!isPasswordCorrect) {
      setAdminAuthError('❌ Incorrect Admin Password. Access denied.');
      return;
    }

    handleOpenEdit(pendingEditExpense);
    setIsAdminAuthModalOpen(false);
    setPendingEditExpense(null);
    setAdminPasswordInput('');
    setAdminAuthError('');
  };

  const handleOpenEdit = (e: any) => {
    setEditingExpenseId(e.id);
    setEditCategory(e.category);
    setEditDate(e.date);
    setEditDescription(e.description);
    setEditCost(e.amount);
    setEditIsAutoGenerated(e.isAutoGenerated);
    setIsEditModalOpen(true);
  };

  const handleEditSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingExpenseId) return;
    await updateExpense(editingExpenseId, {
      category: editCategory,
      date: editDate,
      description: editDescription,
      amount: Number(editCost)
    });
    setIsEditModalOpen(false);
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!expDescription.trim() || expCost <= 0) return;

    addExpense({
      category: expCategory,
      date: expDate,
      description: expDescription,
      amount: Number(expCost)
    });

    // Reset and Close
    setExpDescription('');
    setExpCost(0);
    setIsAddModalOpen(false);
  };

  // Grouped Calculations
  const getCategoryTotal = (cat: ExpenseCategory) => {
    return expenses
      .filter(e => e.category === cat)
      .reduce((sum, e) => sum + e.amount, 0);
  };

  const totalExpense = expenses.reduce((sum, e) => sum + e.amount, 0);

  return (
    <div className="expense-mgmt-page animate-fade-in">
      <div className="page-header-actions">
        <h4 className="section-title">Expense Summary & Logs</h4>
        <button className="btn btn-primary" onClick={() => setIsAddModalOpen(true)}>
          💸 Add Manual Expense
        </button>
      </div>

      {/* Category Summaries */}
      <div className="grid-cols-4 expense-summary-container">
        <div className="glass-card summary-card feed">
          <span className="summary-label">Feed Bills</span>
          <h3 className="summary-value">Rs {getCategoryTotal('Feed').toLocaleString()}</h3>
          <div className="cat-dot feed"></div>
        </div>

        <div className="glass-card summary-card medicine">
          <span className="summary-label">Medicine / Health</span>
          <h3 className="summary-value">Rs {getCategoryTotal('Medicine').toLocaleString()}</h3>
          <div className="cat-dot medicine"></div>
        </div>

        <div className="glass-card summary-card utilities">
          <span className="summary-label">Utilities (Elect. & Water)</span>
          <h3 className="summary-value">Rs {(getCategoryTotal('Electricity') + getCategoryTotal('Water')).toLocaleString()}</h3>
          <div className="cat-dot utilities"></div>
        </div>

        <div className="glass-card summary-card labor">
          <span className="summary-label">Labor & Salaries</span>
          <h3 className="summary-value">Rs {getCategoryTotal('Labor').toLocaleString()}</h3>
          <div className="cat-dot labor"></div>
        </div>
      </div>

      {/* Expense ledger */}
      <div className="glass-card" style={{ marginTop: '2rem' }}>
        <div className="ledger-header">
          <div>
            <h4>Expense Ledger Statement</h4>
            <p className="chart-subtitle">Comprehensive cash outflows including auto-generated stock purchases</p>
          </div>
          <h4 className="color-rose-glow-text">Total Outflow: Rs {totalExpense.toLocaleString()}</h4>
        </div>

        {expenses.length === 0 ? (
          <div className="empty-state">No expenses recorded yet.</div>
        ) : (
          <div className="table-wrapper">
            <table>
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Category</th>
                  <th>Description</th>
                  <th>Type</th>
                  <th>Amount</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {expenses.map(e => (
                  <tr key={e.id}>
                    <td>{e.date}</td>
                    <td>
                      <span className={`badge ${
                        e.category === 'Feed' ? 'badge-amber' : 
                        e.category === 'Medicine' ? 'badge-rose' : 
                        e.category === 'Labor' ? 'badge-emerald' : 'badge-cyan'
                      }`}>
                        {e.category}
                      </span>
                    </td>
                    <td>{e.description}</td>
                    <td>
                      {e.isAutoGenerated ? (
                        <span className="badge badge-cyan text-xxs">Auto-Linked</span>
                      ) : (
                        <span className="badge badge-secondary text-xxs">Manual Log</span>
                      )}
                    </td>
                    <td><b>Rs {e.amount.toFixed(2)}</b></td>
                    <td>
                      <div style={{ display: 'flex', gap: '0.35rem' }}>
                        <button
                          type="button"
                          className="btn btn-secondary btn-xs-custom"
                          onClick={() => handleInitiateEdit(e)}
                        >
                          ✏️ Edit
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Modal: Add Expense */}
      <Modal
        isOpen={isAddModalOpen}
        onClose={() => setIsAddModalOpen(false)}
        title="Add Manual Expense Record"
        footer={
          <>
            <button className="btn btn-secondary" onClick={() => setIsAddModalOpen(false)}>Cancel</button>
            <button className="btn btn-primary" onClick={handleSubmit}>Save Expense</button>
          </>
        }
      >
        <form onSubmit={handleSubmit} className="modal-form-grid">
          <div className="form-row">
            <div className="form-group">
              <label className="form-label">Expense Category</label>
              <select
                className="form-control"
                value={expCategory}
                onChange={e => setExpCategory(e.target.value as ExpenseCategory)}
              >
                <option value="Electricity">Electricity</option>
                <option value="Labor">Labor & Salary</option>
                <option value="Water">Water Supply</option>
                <option value="Other">Other Maintenance</option>
                <option value="Feed">Feed (Alternative log)</option>
                <option value="Medicine">Medicine (Alternative log)</option>
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Billing Date</label>
              <input
                type="date"
                className="form-control"
                value={expDate}
                onChange={e => setExpDate(e.target.value)}
                required
              />
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Amount Cost (Rs)</label>
            <input placeholder="100" type="number"
              step="0.01"
              min="0.01"
              className="form-control"
              value={expCost === 0 ? '' : expCost}
              onChange={e => setExpCost(Number(e.target.value))}
              required
            />
          </div>

          <div className="form-group">
            <label className="form-label">Expense Description</label>
            <input
              type="text"
              className="form-control"
              placeholder="e.g. Paid worker overtime wage, electric shed ventilator fix, etc."
              value={expDescription}
              onChange={e => setExpDescription(e.target.value)}
              maxLength={256}
              required
            />
          </div>
        </form>
      </Modal>

      {/* Modal: Edit Expense */}
      <Modal
        isOpen={isEditModalOpen}
        onClose={() => setIsEditModalOpen(false)}
        title="✏️ Edit Expense Record"
        footer={
          <div style={{ display: 'flex', justifyContent: 'space-between', width: '100%', alignItems: 'center' }}>
            <button
              type="button"
              className="btn btn-danger"
              onClick={() => {
                if (window.confirm('Are you sure you want to delete this expense record? Associated purchases/records will be deleted.')) {
                  deleteExpense(editingExpenseId);
                  setIsEditModalOpen(false);
                }
              }}
            >
              🗑️ Delete Expense
            </button>
            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <button type="button" className="btn btn-secondary" onClick={() => setIsEditModalOpen(false)}>Cancel</button>
              <button type="button" className="btn btn-primary" onClick={handleEditSubmit}>Save Changes</button>
            </div>
          </div>
        }
      >
        <form onSubmit={handleEditSubmit} className="modal-form-grid">
          {editIsAutoGenerated && (
            <div className="form-group" style={{ background: 'rgba(245,158,11,0.08)', border: '1px solid rgba(245,158,11,0.2)', padding: '0.65rem 0.85rem', borderRadius: 'var(--radius-sm)', fontSize: '0.8rem', color: 'var(--color-amber)', marginBottom: '0.5rem' }}>
              ⚠️ This is an auto-linked expense. Modifying its amount or date will also update the linked Feed Purchase or Medical Record.
            </div>
          )}

          <div className="form-row">
            <div className="form-group">
              <label className="form-label">Expense Category</label>
              <select
                className="form-control"
                value={editCategory}
                onChange={e => setEditCategory(e.target.value as ExpenseCategory)}
                disabled={editIsAutoGenerated}
              >
                <option value="Electricity">Electricity</option>
                <option value="Labor">Labor & Salary</option>
                <option value="Water">Water Supply</option>
                <option value="Other">Other Maintenance</option>
                <option value="Feed">Feed (Alternative log)</option>
                <option value="Medicine">Medicine (Alternative log)</option>
              </select>
            </div>
            <div className="form-group">
              <label className="form-label">Billing Date</label>
              <input
                type="date"
                className="form-control"
                value={editDate}
                onChange={e => setEditDate(e.target.value)}
                required
              />
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Amount Cost (Rs)</label>
            <input placeholder="100" type="number"
              step="0.01"
              min="0.01"
              className="form-control"
              value={editCost === 0 ? '' : editCost}
              onChange={e => setEditCost(Number(e.target.value))}
              required
            />
          </div>

          <div className="form-group">
            <label className="form-label">Expense Description</label>
            <input
              type="text"
              className="form-control"
              value={editDescription}
              onChange={e => setEditDescription(e.target.value)}
              maxLength={256}
              required
              disabled={editIsAutoGenerated}
            />
          </div>
        </form>
      </Modal>

      {/* ── Admin Password Approval Modal for Editing Expense ── */}
      <Modal
        isOpen={isAdminAuthModalOpen}
        onClose={() => {
          setIsAdminAuthModalOpen(false);
          setPendingEditExpense(null);
          setAdminPasswordInput('');
          setAdminAuthError('');
        }}
        title="🔐 Security Verification: Admin Approval Required"
        footer={
          <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end', width: '100%' }}>
            <button
              className="btn btn-secondary"
              type="button"
              onClick={() => {
                setIsAdminAuthModalOpen(false);
                setPendingEditExpense(null);
                setAdminPasswordInput('');
                setAdminAuthError('');
              }}
            >
              Cancel
            </button>
            <button className="btn btn-success" type="button" onClick={handleVerifyAdminAndExecute}>
              🔑 Verify & Open Editor
            </button>
          </div>
        }
      >
        <form onSubmit={handleVerifyAdminAndExecute} style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <div style={{ background: 'rgba(245, 158, 11, 0.1)', border: '1px solid rgba(245, 158, 11, 0.3)', padding: '0.75rem 1rem', borderRadius: 'var(--radius-md)' }}>
            <p style={{ margin: 0, fontSize: '0.85rem', color: 'var(--text-primary)', fontWeight: 600 }}>
              🔒 Admin Password Required
            </p>
            <p style={{ margin: '0.2rem 0 0 0', fontSize: '0.78rem', color: 'var(--text-muted)' }}>
              Modifying or editing a recorded expense entry requires administrator verification.
            </p>
          </div>

          <div className="form-group">
            <label className="form-label" style={{ fontWeight: 600 }}>Admin Password</label>
            <input
              type="password"
              className="form-control"
              placeholder="Enter Admin Password"
              value={adminPasswordInput}
              onChange={ev => {
                setAdminPasswordInput(ev.target.value);
                setAdminAuthError('');
              }}
              autoFocus
              required
            />
          </div>

          {adminAuthError && (
            <div style={{ color: 'var(--color-rose)', fontSize: '0.82rem', fontWeight: 600 }}>
              {adminAuthError}
            </div>
          )}
        </form>
      </Modal>

      <style>{`
        .expense-mgmt-page {
          display: flex;
          flex-direction: column;
        }

        .page-header-actions {
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin-bottom: var(--spacing-lg);
        }

        .expense-summary-container {
          margin-top: var(--spacing-sm);
        }

        .summary-card {
          display: flex;
          flex-direction: column;
          gap: 0.25rem;
          position: relative;
        }

        .summary-label {
          font-size: 0.78rem;
          text-transform: uppercase;
          letter-spacing: 0.05em;
          color: var(--text-secondary);
        }

        .summary-value {
          font-size: 1.6rem;
          font-weight: 700;
          color: var(--text-primary);
        }

        .cat-dot {
          position: absolute;
          width: 8px;
          height: 8px;
          border-radius: 50%;
          right: var(--spacing-md);
          top: var(--spacing-md);
        }

        .cat-dot.feed { background: var(--color-amber); }
        .cat-dot.medicine { background: var(--color-rose); }
        .cat-dot.utilities { background: var(--color-cyan); }
        .cat-dot.labor { background: var(--color-emerald); }

        .ledger-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 1.25rem;
          flex-wrap: wrap;
          gap: var(--spacing-md);
        }

        .color-rose-glow-text {
          color: #fca5a5;
        }

        .btn-xs-custom {
          padding: 0.25rem 0.5rem;
          font-size: 0.72rem;
          font-weight: 600;
          border-radius: var(--radius-sm);
        }

        .text-xxs {
          font-size: 0.6rem;
          padding: 0.1rem 0.35rem;
        }
      `}</style>
    </div>
  );
};

