import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '../lib/supabaseClient';

// ==========================================
// TYPES AND INTERFACES
// ==========================================

export type BirdType = 'Broiler' | 'Layer';
export type BatchStatus = 'Active' | 'Sold';

export interface MortalityLog {
  id: string;
  date: string;
  quantity: number;
  reason: string;
}

export interface BirdBatch {
  id: string;
  type: BirdType;
  arrivalDate: string;
  initialQuantity: number;
  currentQuantity: number;
  purchasePrice: number; // price per bird
  status: BatchStatus;
  mortalityLogs: MortalityLog[];
  initialQuantityKg?: number;
  purchasePricePerKg?: number;
}

export type FeedType = 'Starter' | 'Grower' | 'Finisher' | 'Layer Mash';

export interface FeedPurchase {
  id: string;
  date: string;
  feedType: FeedType;
  quantityKg: number;
  cost: number;
  vendor: string;
}

export interface FeedConsumption {
  id: string;
  date: string;
  feedType: FeedType;
  batchId: string;
  quantityKg: number;
}

export type VaccineStatus = 'Pending' | 'Completed';

export interface VaccineSchedule {
  id: string;
  vaccineName: string;
  batchId: string;
  scheduledDate: string;
  status: VaccineStatus;
}

export interface MedicalRecord {
  id: string;
  date: string;
  batchId: string;
  disease: string;
  medicine: string;
  dosage: string;
  cost: number;
}

export interface EggCollection {
  date: string;
  collectedQty: number;
  damagedQty: number;
  netQty: number;
}

export type SaleType = 'Bird' | 'Egg';

export interface Sale {
  id: string;
  invoiceId: string;
  type: SaleType;
  date: string;
  customerName: string;
  customerContact: string;
  quantity: number; // number of birds or crates (30 eggs/crate)
  unitPrice: number;
  totalAmount: number;
  batchId?: string; // If bird sale
  details?: string;
  weightKg?: number;
  pricePerKg?: number;
  amountPaid?: number;
  transportCharges?: number;
  otherCharges?: number;
  extraChargesList?: {name: string, amount: number}[];
  oldBalance?: number;
  updatedAt?: string;
}

export type ExpenseCategory = 'Feed' | 'Medicine' | 'Electricity' | 'Labor' | 'Water' | 'Other';

export interface Expense {
  id: string;
  category: ExpenseCategory;
  date: string;
  description: string;
  amount: number;
  isAutoGenerated: boolean;
  referenceId?: string; // ID of feed purchase or medical record
}

export type UserRole = 'Admin' | 'Employee';

export interface User {
  username: string;
  role: UserRole;
}

export interface UserCredential {
  username: string;
  password: string;
  role: UserRole;
  approved: boolean;
  fullName?: string;
  dob?: string;
  securityQuestion?: string;
  securityAnswer?: string;
}

export type PendingSubmissionType = 
  | 'Mortality'
  | 'EggCollection'
  | 'FeedConsumption'
  | 'FeedPurchase'
  | 'VaccineSchedule'
  | 'VaccineStatusUpdate'
  | 'MedicalRecord'
  | 'BirdBatch';

export interface PendingSubmission {
  id: string;
  type: PendingSubmissionType;
  submittedBy: string;
  submittedAt: string;
  data: any;
  status: 'Pending' | 'Approved' | 'Rejected';
  reviewedBy?: string;
  reviewedAt?: string;
  rejectionReason?: string;
}

interface FarmContextType {
  currentUser: User | null;
  login: (username: string, role: UserRole) => boolean;
  logout: () => void;
  batches: BirdBatch[];
  addBatch: (batch: Omit<BirdBatch, 'currentQuantity' | 'mortalityLogs' | 'status'>) => void;
  deleteBatch: (batchId: string) => void;
  sellBatch: (
    batchId: string,
    quantity: number,
    pricePerBird: number,
    customerName: string,
    customerContact: string,
    weightKg?: number,
    pricePerKg?: number,
    totalAmount?: number,
    amountPaid?: number,
    transport?: number,
    other?: number,
    oldBalance?: number
  ) => void;
  logMortality: (batchId: string, quantity: number, reason: string, date: string) => void;
  updateMortalityLog: (id: string, batchId: string, oldQty: number, newQty: number, reason: string, date: string) => Promise<void>;
  deleteMortalityLog: (id: string, batchId: string, qty: number) => Promise<void>;
  feedPurchases: FeedPurchase[];
  addFeedPurchase: (purchase: Omit<FeedPurchase, 'id'>) => void;
  feedConsumption: FeedConsumption[];
  addFeedConsumption: (consumption: Omit<FeedConsumption, 'id'>) => void;
  vaccines: VaccineSchedule[];
  addVaccineSchedule: (schedule: Omit<VaccineSchedule, 'id' | 'status'>) => void;
  updateVaccineStatus: (id: string, status: VaccineStatus) => void;
  deleteVaccineSchedule: (id: string) => void;
  medicalRecords: MedicalRecord[];
  addMedicalRecord: (record: Omit<MedicalRecord, 'id'>) => void;
  deleteMedicalRecord: (id: string) => Promise<void>;
  eggCollections: EggCollection[];
  addEggCollection: (collection: EggCollection) => void;
  deleteEggCollection: (date: string) => void;
  sales: Sale[];
  addEggSale: (sale: Omit<Sale, 'id' | 'invoiceId' | 'type' | 'batchId'>) => void;
  deleteSale: (saleId: string) => Promise<void>;
  expenses: Expense[];
  addExpense: (expense: Omit<Expense, 'id' | 'isAutoGenerated'>) => void;
  deleteExpense: (id: string) => void;
  getFeedStock: (type: FeedType) => number;
  updateBatch: (batchId: string, updated: Omit<BirdBatch, 'id' | 'mortalityLogs'>) => Promise<void>;
  updateFeedPurchase: (purchaseId: string, updated: Omit<FeedPurchase, 'id'>) => Promise<void>;
  deleteFeedPurchase: (purchaseId: string) => Promise<void>;
  updateFeedConsumption: (consumptionId: string, updated: Omit<FeedConsumption, 'id'>) => Promise<void>;
  updateVaccineSchedule: (id: string, updated: Omit<VaccineSchedule, 'id'>) => Promise<void>;
  updateMedicalRecord: (recordId: string, updated: Omit<MedicalRecord, 'id'>) => Promise<void>;
  updateEggCollection: (originalDate: string, updated: EggCollection) => Promise<void>;
  updateSale: (saleId: string, updated: Omit<Sale, 'id' | 'invoiceId'>) => Promise<void>;
  updateExpense: (id: string, updated: Omit<Expense, 'id' | 'isAutoGenerated'>) => Promise<void>;
  usersList: UserCredential[];
  registerUser: (user: UserCredential) => { success: boolean; message: string };
  approveUser: (username: string) => void;
  updateUserRole: (username: string, role: UserRole) => void;
  updateUserProfile: (oldUsername: string, newUsername: string, newPassword?: string, oldPassword?: string) => { success: boolean; message: string };
  resetUserPassword: (username: string, newPassword: string) => { success: boolean; message: string };
  verifyAndResetPassword: (username: string, dob: string, answer: string, newPassword: string) => { success: boolean; message: string };
  deleteUser: (username: string) => void;
  pendingSubmissions: PendingSubmission[];
  submitForApproval: (type: PendingSubmissionType, data: any) => PendingSubmission;
  approveSubmission: (submissionId: string) => Promise<void>;
  rejectSubmission: (submissionId: string, reason?: string) => void;
  deletePendingSubmission: (submissionId: string) => void;
  isLoading: boolean;
}

// ==========================================
// CONTEXT CREATION & PROVIDER
// ==========================================

const FarmContext = createContext<FarmContextType | undefined>(undefined);

export const FarmProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  // Session User (Kept in LocalStorage for dev auth simplicity)
  const [currentUser, setCurrentUser] = useState<User | null>(() => {
    try {
      const saved = localStorage.getItem('poultry_user');
      if (!saved) return null;
      const parsed = JSON.parse(saved);
      // Validate shape to guard against tampered storage
      if (
        parsed &&
        typeof parsed.username === 'string' &&
        (parsed.role === 'Admin' || parsed.role === 'Employee')
      ) {
        return parsed as User;
      }
      return null;
    } catch {
      localStorage.removeItem('poultry_user');
      return null;
    }
  });

  // Load users database
  const [usersList, setUsersList] = useState<UserCredential[]>(() => {
    try {
      const defaultUsers: UserCredential[] = [
        {
          username: 'admin',
          password: 'admin',
          role: 'Admin',
          approved: true,
          fullName: 'Farm Administrator',
          dob: '2001-02-23',
          securityQuestion: 'What is the name of your farm?',
          securityAnswer: 'Aksha Farm'
        },
        {
          username: 'employee',
          password: 'employee',
          role: 'Employee',
          approved: true,
          fullName: 'Aksha Staff Member',
          dob: '1995-05-15',
          securityQuestion: 'What is the name of your farm?',
          securityAnswer: 'Aksha Farm'
        }
      ];
      const stored = localStorage.getItem('poultry_users_list');
      if (!stored) {
        localStorage.setItem('poultry_users_list', JSON.stringify(defaultUsers));
        return defaultUsers;
      }
      const parsed = JSON.parse(stored) as UserCredential[];
      return parsed.map(u => {
        const isAdmin = u.username.toLowerCase() === 'admin';
        const matchDefault = defaultUsers.find(d => d.username.toLowerCase() === u.username.toLowerCase());
        return {
          ...u,
          approved: u.approved !== undefined ? u.approved : true,
          fullName: u.fullName || matchDefault?.fullName || u.username,
          dob: isAdmin ? '2001-02-23' : (u.dob || matchDefault?.dob || '1995-05-15'),
          securityQuestion: u.securityQuestion || matchDefault?.securityQuestion || 'What is the name of your farm?',
          securityAnswer: u.securityAnswer || matchDefault?.securityAnswer || 'Aksha Farm'
        };
      });
    } catch {
      return [];
    }
  });

  // Keep localStorage in sync with usersList state updates
  useEffect(() => {
    localStorage.setItem('poultry_users_list', JSON.stringify(usersList));
  }, [usersList]);

  // Core Farm States
  const [batches, setBatches] = useState<BirdBatch[]>([]);
  const [feedPurchases, setFeedPurchases] = useState<FeedPurchase[]>([]);
  const [feedConsumption, setFeedConsumption] = useState<FeedConsumption[]>([]);
  const [vaccines, setVaccines] = useState<VaccineSchedule[]>([]);
  const [medicalRecords, setMedicalRecords] = useState<MedicalRecord[]>([]);
  const [eggCollections, setEggCollections] = useState<EggCollection[]>([]);
  const [sales, setSales] = useState<Sale[]>([]);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // ----------------------------------------------------
  // FETCH ALL DATA FROM SUPABASE
  // ----------------------------------------------------
  const fetchAllData = async () => {
    try {
      const [
        { data: batchesData },
        { data: mortalityData },
        { data: feedPurchasesData },
        { data: feedConsumptionData },
        { data: vaccinesData },
        { data: medicalRecordsData },
        { data: eggCollectionsData },
        { data: salesData },
        { data: expensesData },
        { data: usersData, error: usersErr }
      ] = await Promise.all([
        supabase.from('batches').select('*'),
        supabase.from('mortality_logs').select('*'),
        supabase.from('feed_purchases').select('*'),
        supabase.from('feed_consumptions').select('*'),
        supabase.from('vaccine_schedules').select('*'),
        supabase.from('medical_records').select('*'),
        supabase.from('egg_collections').select('*'),
        supabase.from('sales').select('*'),
        supabase.from('expenses').select('*'),
        supabase.from('users').select('*')
      ]);

      if (usersData && usersData.length > 0) {
        const formattedUsers: UserCredential[] = usersData.map((u: any) => ({
          username: u.username,
          password: u.password,
          role: u.role as UserRole,
          approved: Boolean(u.approved),
          fullName: u.full_name || u.username,
          dob: u.dob || (u.username === 'admin' ? '2001-02-23' : '1995-05-15'),
          securityQuestion: u.security_question || 'What is the name of your farm?',
          securityAnswer: u.security_answer || 'Aksha Farm'
        }));
        setUsersList(formattedUsers);
      } else if (!usersErr) {
        // Seed default admin and employee into Supabase users table
        await supabase.from('users').upsert([
          {
            username: 'admin',
            password: 'admin',
            role: 'Admin',
            approved: true,
            full_name: 'Farm Administrator',
            dob: '2001-02-23',
            security_question: 'What is the name of your farm?',
            security_answer: 'Aksha Farm'
          },
          {
            username: 'employee',
            password: 'employee',
            role: 'Employee',
            approved: true,
            full_name: 'Aksha Staff Member',
            dob: '1995-05-15',
            security_question: 'What is the name of your farm?',
            security_answer: 'Aksha Farm'
          }
        ]);
      }

      // Map Batches and their Mortality Logs
      const formattedBatches = (batchesData || []).map((b: any) => ({
        id: b.id,
        type: b.type as BirdType,
        arrivalDate: b.arrival_date,
        initialQuantity: b.initial_quantity,
        currentQuantity: b.current_quantity,
        purchasePrice: Number(b.purchase_price),
        status: b.status as BatchStatus,
        initialQuantityKg: b.initial_quantity_kg ? Number(b.initial_quantity_kg) : undefined,
        purchasePricePerKg: b.purchase_price_per_kg ? Number(b.purchase_price_per_kg) : undefined,
        mortalityLogs: (mortalityData || [])
          .filter((m: any) => m.batch_id === b.id)
          .map((m: any) => ({
            id: m.id,
            date: m.date,
            quantity: m.quantity,
            reason: m.reason
          }))
      }));
      setBatches(formattedBatches);

      // Map Feed Purchases
      setFeedPurchases((feedPurchasesData || []).map((p: any) => ({
        id: p.id,
        date: p.date,
        feedType: p.feed_type as FeedType,
        quantityKg: Number(p.quantity_kg),
        cost: Number(p.cost),
        vendor: p.vendor
      })));

      // Map Feed Consumptions
      setFeedConsumption((feedConsumptionData || []).map((c: any) => ({
        id: c.id,
        date: c.date,
        feedType: c.feed_type as FeedType,
        batchId: c.batch_id,
        quantityKg: Number(c.quantity_kg)
      })));

      // Map Vaccine Schedules
      setVaccines((vaccinesData || []).map((v: any) => ({
        id: v.id,
        vaccineName: v.vaccine_name,
        batchId: v.batch_id,
        scheduledDate: v.scheduled_date,
        status: v.status as VaccineStatus
      })));

      // Map Medical Records
      setMedicalRecords((medicalRecordsData || []).map((m: any) => ({
        id: m.id,
        date: m.date,
        batchId: m.batch_id,
        disease: m.disease,
        medicine: m.medicine,
        dosage: m.dosage,
        cost: Number(m.cost)
      })));

      // Map Egg Collections
      const mappedEggCols = (eggCollectionsData || []).map((e: any) => ({
        date: e.date,
        collectedQty: e.collectedQty || e.collected_qty,
        damagedQty: e.damagedQty || e.damaged_qty,
        netQty: e.netQty || e.net_qty
      }));
      setEggCollections(mappedEggCols.sort((a: EggCollection, b: EggCollection) => new Date(b.date).getTime() - new Date(a.date).getTime()));

      // Map Sales
      const localPayments = (() => {
        try {
          return JSON.parse(localStorage.getItem('aksha_invoice_payments') || '{}');
        } catch {
          return {};
        }
      })();
      const paidIdsSet = new Set<string>();
      try {
        const storedPaid = JSON.parse(localStorage.getItem('aksha_paid_invoices') || '[]');
        storedPaid.forEach((id: string) => paidIdsSet.add(id));
      } catch {}

      setSales((salesData || []).map((s: any) => {
        const total = Number(s.total_amount);
        let amtPaid = 0;
        if (s.amount_paid !== undefined && s.amount_paid !== null) {
          amtPaid = Number(s.amount_paid);
        } else if (localPayments[s.id] !== undefined) {
          amtPaid = Number(localPayments[s.id]);
        } else if (paidIdsSet.has(s.id)) {
          amtPaid = total;
        }

        let transport = 0;
        let other = 0;
        let oldBal = 0;
        let extraList = [];
        let displayDetails = s.details || '';
        let updatedAt = s.id;

        if (s.details && s.details.trim().startsWith('{')) {
          try {
            const parsed = JSON.parse(s.details);
            transport = Number(parsed.transport || 0);
            other = Number(parsed.other || 0);
            oldBal = Number(parsed.oldBalance || 0);
            extraList = parsed.extraList || [];
            displayDetails = parsed.remarks || '';
            updatedAt = parsed.updatedAt || s.id;
          } catch {}
        }

        return {
          id: s.id,
          invoiceId: s.invoice_id,
          type: s.type as SaleType,
          date: s.date,
          customerName: s.customer_name,
          customerContact: s.customer_contact,
          quantity: Number(s.quantity),
          unitPrice: Number(s.unit_price),
          totalAmount: total,
          batchId: s.batch_id || undefined,
          details: displayDetails,
          weightKg: s.weight_kg ? Number(s.weight_kg) : undefined,
          pricePerKg: s.price_per_kg ? Number(s.price_per_kg) : undefined,
          amountPaid: amtPaid,
          transportCharges: transport,
          otherCharges: other,
          extraChargesList: extraList,
          oldBalance: oldBal,
          updatedAt: updatedAt
        };
      }));

      // Map Expenses
      setExpenses((expensesData || []).map((ex: any) => ({
        id: ex.id,
        category: ex.category as ExpenseCategory,
        date: ex.date,
        description: ex.description,
        amount: Number(ex.amount),
        isAutoGenerated: ex.is_auto_generated,
        referenceId: ex.reference_id || undefined
      })));

    } catch (err) {
      console.error('Unexpected error loading farm data:', err);
    } finally {
      setIsLoading(false);
    }
  };

  // Sync session user
  useEffect(() => {
    if (currentUser) {
      localStorage.setItem('poultry_user', JSON.stringify(currentUser));
    } else {
      localStorage.removeItem('poultry_user');
    }
  }, [currentUser]);

  // Load initial data and subscribe to realtime updates
  useEffect(() => {
    fetchAllData();

    // Subscribe to schema changes across all public tables
    const channel = supabase
      .channel('realtime-farm-updates')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public' },
        () => {
          // Trigger a clean refetch when any database write occurs
          fetchAllData();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, []);

  // ==========================================
  // UTILITIES & STATE MUTATORS
  // ==========================================

  // Authentication (Local Session storage)
  const login = (username: string, role: UserRole): boolean => {
    // Validate that the username is a non-empty string and role is an allowed value
    const trimmed = username.trim();
    if (!trimmed || trimmed.length > 64) return false;
    if (role !== 'Admin' && role !== 'Employee') return false;

    setCurrentUser({ username: trimmed, role });
    return true;
  };

  const logout = () => {
    setCurrentUser(null);
  };

  // User Management
  const registerUser = (newUser: UserCredential): { success: boolean; message: string } => {
    const trimmedUser = newUser.username.trim();
    if (!trimmedUser || newUser.password.length < 4) {
      return { success: false, message: 'Invalid credentials. Password must be at least 4 characters.' };
    }
    const userExists = usersList.some(
      u => u.username.toLowerCase() === trimmedUser.toLowerCase()
    );

    if (userExists) {
      return { success: false, message: `A user with username "${trimmedUser}" already exists.` };
    }

    const created = { ...newUser, username: trimmedUser };
    setUsersList(prev => [...prev, created]);

    // Sync to Supabase users table
    supabase.from('users').upsert({
      username: trimmedUser,
      password: newUser.password,
      role: newUser.role,
      approved: Boolean(newUser.approved),
      full_name: newUser.fullName || trimmedUser,
      dob: newUser.dob || '2001-02-23',
      security_question: newUser.securityQuestion || 'What is the name of your farm?',
      security_answer: newUser.securityAnswer || 'Aksha Farm'
    }).then((res: any) => {
      if (res.error) console.error('Error saving user to Supabase:', res.error);
    });

    return { success: true, message: 'Account created successfully! Please wait for an administrator to approve it.' };
  };

  const approveUser = (username: string) => {
    setUsersList(prev =>
      prev.map(u => (u.username.toLowerCase() === username.toLowerCase() ? { ...u, approved: true } : u))
    );
    supabase.from('users').update({ approved: true }).eq('username', username).then((res: any) => {
      if (res.error) console.error('Error approving user in Supabase:', res.error);
    });
  };

  const updateUserRole = (username: string, role: UserRole) => {
    setUsersList(prev =>
      prev.map(u => (u.username.toLowerCase() === username.toLowerCase() ? { ...u, role } : u))
    );
    supabase.from('users').update({ role }).eq('username', username).then((res: any) => {
      if (res.error) console.error('Error updating role in Supabase:', res.error);
    });
  };

  const updateUserProfile = (
    oldUsername: string,
    newUsername: string,
    newPassword?: string,
    oldPassword?: string
  ): { success: boolean; message: string } => {
    const trimmedNewUsername = newUsername.trim();
    if (!trimmedNewUsername) {
      return { success: false, message: 'Username cannot be empty.' };
    }

    // Find the user to update to check their password
    const userToUpdate = usersList.find(u => u.username.toLowerCase() === oldUsername.toLowerCase());
    if (!userToUpdate) {
      return { success: false, message: 'User not found.' };
    }

    // If username is changing, check if it is taken
    if (oldUsername.toLowerCase() !== trimmedNewUsername.toLowerCase()) {
      const exists = usersList.some(
        u => u.username.toLowerCase() === trimmedNewUsername.toLowerCase()
      );
      if (exists) {
        return { success: false, message: `Username "${trimmedNewUsername}" is already taken.` };
      }
    }

    // If a new password is provided, we MUST verify the old password
    if (newPassword) {
      if (!oldPassword) {
        return { success: false, message: 'Please provide your current password to set a new password.' };
      }
      if (userToUpdate.password !== oldPassword) {
        return { success: false, message: 'Incorrect current password.' };
      }
      if (newPassword.length < 4) {
        return { success: false, message: 'Password must be at least 4 characters.' };
      }
    }

    setUsersList(prev =>
      prev.map(u => {
        if (u.username.toLowerCase() === oldUsername.toLowerCase()) {
          return {
            ...u,
            username: trimmedNewUsername,
            ...(newPassword ? { password: newPassword } : {})
          };
        }
        return u;
      })
    );

    if (currentUser && currentUser.username.toLowerCase() === oldUsername.toLowerCase()) {
      setCurrentUser(prev => prev ? { ...prev, username: trimmedNewUsername } : null);
    }

    supabase.from('users').update({
      username: trimmedNewUsername,
      ...(newPassword ? { password: newPassword } : {})
    }).eq('username', oldUsername).then((res: any) => {
      if (res.error) console.error('Error updating user profile in Supabase:', res.error);
    });

    return { success: true, message: 'Profile updated successfully!' };
  };

  const resetUserPassword = (username: string, newPassword: string): { success: boolean; message: string } => {
    const trimmed = username.trim();
    if (!trimmed) {
      return { success: false, message: 'Username is required.' };
    }
    if (!newPassword || newPassword.length < 4) {
      return { success: false, message: 'Password must be at least 4 characters long.' };
    }

    const userToUpdate = usersList.find(u => u.username.toLowerCase() === trimmed.toLowerCase());
    if (!userToUpdate) {
      return { success: false, message: `No account found for username "${trimmed}".` };
    }

    setUsersList(prev =>
      prev.map(u => (u.username.toLowerCase() === trimmed.toLowerCase() ? { ...u, password: newPassword } : u))
    );

    supabase.from('users').update({ password: newPassword }).eq('username', trimmed).then((res: any) => {
      if (res.error) console.error('Error resetting password in Supabase:', res.error);
    });

    return { success: true, message: 'Password updated successfully! You can now log in with your new password.' };
  };

  const verifyAndResetPassword = (
    username: string,
    dob: string,
    answer: string,
    newPassword: string
  ): { success: boolean; message: string } => {
    const trimmedUser = username.trim();
    const trimmedDob = dob.trim();
    const trimmedAnswer = answer.trim();
    if (!trimmedUser || !trimmedDob || !trimmedAnswer || !newPassword) {
      return { success: false, message: 'Please fill in all required fields (DOB, Security Answer, New Password).' };
    }
    if (newPassword.length < 4) {
      return { success: false, message: 'New password must be at least 4 characters long.' };
    }

    const user = usersList.find(u => u.username.toLowerCase() === trimmedUser.toLowerCase());
    if (!user) {
      return { success: false, message: `No account found with username "${trimmedUser}".` };
    }

    // Verify DOB if account has DOB set
    if (user.dob && user.dob !== trimmedDob) {
      return { success: false, message: 'Date of Birth does not match account records.' };
    }

    // Verify Security Answer
    const storedAnswer = user.securityAnswer ? user.securityAnswer.trim().toLowerCase() : 'aksha farm';
    if (storedAnswer !== trimmedAnswer.toLowerCase()) {
      return { success: false, message: 'Incorrect security answer. Verification failed.' };
    }

    setUsersList(prev =>
      prev.map(u => (u.username.toLowerCase() === trimmedUser.toLowerCase() ? { ...u, password: newPassword } : u))
    );

    supabase.from('users').update({ password: newPassword }).eq('username', trimmedUser).then((res: any) => {
      if (res.error) console.error('Error resetting password in Supabase:', res.error);
    });

    return { success: true, message: 'Identity verification successful! Your password has been updated. Please sign in.' };
  };

  const deleteUser = (username: string) => {
    setUsersList(prev => prev.filter(u => u.username.toLowerCase() !== username.toLowerCase()));
    supabase.from('users').delete().eq('username', username).then((res: any) => {
      if (res.error) console.error('Error deleting user from Supabase:', res.error);
    });
  };

  // 1. Bird Management
  const addBatch = async (batch: Omit<BirdBatch, 'currentQuantity' | 'mortalityLogs' | 'status'>) => {
    const newBatch: any = {
      id: batch.id,
      type: batch.type,
      arrival_date: batch.arrivalDate,
      initial_quantity: batch.initialQuantity,
      current_quantity: batch.initialQuantity,
      purchase_price: batch.purchasePrice,
      status: 'Active',
      initial_quantity_kg: batch.type === 'Broiler' ? batch.initialQuantityKg : null,
      purchase_price_per_kg: batch.type === 'Broiler' ? batch.purchasePricePerKg : null
    };

    const cost = batch.type === 'Broiler' && batch.initialQuantityKg && batch.purchasePricePerKg
      ? batch.initialQuantityKg * batch.purchasePricePerKg
      : batch.initialQuantity * batch.purchasePrice;

    const newExpense = {
      id: `exp-${Date.now()}`,
      category: 'Other',
      date: batch.arrivalDate,
      description: `Bird Batch Purchase: ${batch.type} - ${batch.initialQuantity} birds (ID: ${batch.id})`,
      amount: cost,
      is_auto_generated: true,
      reference_id: batch.id
    };

    try {
      const { error: batchErr } = await supabase.from('batches').insert(newBatch);
      if (batchErr) {
        if (batchErr.code === 'PGRST204' || batchErr.message?.includes('initial_quantity_kg') || batchErr.message?.includes('schema cache')) {
          console.warn("Supabase schema cache missing initial_quantity_kg columns. Retrying without these columns.");
          alert("Notice: Broiler weight-based columns (initial_quantity_kg, purchase_price_per_kg) do not exist in your Supabase database. The batch will be saved as a standard bird batch. To enable full weight tracking, please run the SQL migration at the bottom of your schema.sql file in the Supabase SQL Editor.");
          
          delete newBatch.initial_quantity_kg;
          delete newBatch.purchase_price_per_kg;
          
          const { error: retryErr } = await supabase.from('batches').insert(newBatch);
          if (retryErr) throw retryErr;
        } else {
          throw batchErr;
        }
      }

      const { error: expErr } = await supabase.from('expenses').insert(newExpense);
      if (expErr) throw expErr;

      fetchAllData();
    } catch (err: any) {
      console.error('Failed to add batch:', err);
      alert(`Error adding batch: ${err.message || err}`);
    }
  };

  const sellBatch = async (
    batchId: string,
    quantity: number,
    pricePerBird: number,
    customerName: string,
    customerContact: string,
    weightKg?: number,
    pricePerKg?: number,
    totalAmount?: number,
    amountPaid?: number,
    transport?: number,
    other?: number,
    oldBalance?: number
  ) => {
    try {
      const { data: batch } = await supabase
        .from('batches')
        .select('current_quantity')
        .eq('id', batchId)
        .single();

      if (!batch) return;

      const newCurrentQty = Math.max(0, batch.current_quantity - quantity);
      const newStatus = newCurrentQty === 0 ? 'Sold' : 'Active';

      const subtotal = totalAmount ?? (weightKg && pricePerKg ? weightKg * pricePerKg : quantity * pricePerBird);
      const transportAmt = transport || 0;
      const otherAmt = other || 0;
      const computedTotal = subtotal + transportAmt + otherAmt;
      const finalPaid = amountPaid ?? computedTotal;

      const saleId = `s-${Date.now()}`;
      const invoiceNum = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;

      const detailsPayload = JSON.stringify({
        remarks: `Sold ${quantity} birds from Batch ${batchId}${weightKg ? ` (${weightKg} kg @ Rs ${pricePerKg}/kg)` : ''}`,
        transport: transportAmt,
        other: otherAmt,
        oldBalance: oldBalance || 0,
        updatedAt: new Date().toISOString()
      });

      const newSale: any = {
        id: saleId,
        invoice_id: invoiceNum,
        type: 'Bird',
        date: new Date().toISOString().split('T')[0],
        customer_name: customerName,
        customer_contact: customerContact,
        quantity,
        unit_price: pricePerBird,
        total_amount: computedTotal,
        amount_paid: finalPaid,
        batch_id: batchId,
        details: detailsPayload,
        weight_kg: weightKg || null,
        price_per_kg: pricePerKg || null
      };

      try {
        const { error: saleErr } = await supabase.from('sales').insert(newSale);
        if (saleErr) {
          let currentErr = saleErr;

          // 1st Fallback: amount_paid
          if (currentErr.code === '42703' || currentErr.message?.includes('amount_paid')) {
            console.warn("Supabase schema missing amount_paid column. Saving to localStorage and retrying insert.");
            
            const localPayments = JSON.parse(localStorage.getItem('aksha_invoice_payments') || '{}');
            localPayments[saleId] = finalPaid;
            localStorage.setItem('aksha_invoice_payments', JSON.stringify(localPayments));

            if (finalPaid >= computedTotal) {
              const paidIds = JSON.parse(localStorage.getItem('aksha_paid_invoices') || '[]');
              if (!paidIds.includes(saleId)) {
                paidIds.push(saleId);
                localStorage.setItem('aksha_paid_invoices', JSON.stringify(paidIds));
              }
            }

            delete newSale.amount_paid;
            
            const { error: retryErr } = await supabase.from('sales').insert(newSale);
            if (retryErr) currentErr = retryErr;
            else currentErr = null as any;
          }

          // 2nd Fallback: weight_kg / price_per_kg
          if (currentErr && (currentErr.code === 'PGRST204' || currentErr.message?.includes('weight_kg') || currentErr.message?.includes('schema cache') || currentErr.message?.includes('price_per_kg'))) {
            console.warn("Supabase schema cache missing weight_kg columns. Retrying without weight columns.");
            
            delete newSale.weight_kg;
            delete newSale.price_per_kg;
            newSale.total_amount = quantity * pricePerBird;
            
            const { error: retryErr2 } = await supabase.from('sales').insert(newSale);
            if (retryErr2) throw retryErr2;
          } else if (currentErr) {
            throw currentErr;
          }
        }

        const { error: batchErr } = await supabase
          .from('batches')
          .update({ current_quantity: newCurrentQty, status: newStatus })
          .eq('id', batchId);
        
        if (batchErr) throw batchErr;

      } catch (err: any) {
        console.error('Failed to save sale:', err);
        alert(`Error completing sale: ${err.message || err}`);
      }

      setBatches(prev => prev.map(b => {
        if (b.id === batchId) {
          return {
            ...b,
            currentQuantity: newCurrentQty,
            status: newStatus
          };
        }
        return b;
      }));

      fetchAllData();
    } catch (err) {
      console.error('Failed to sell batch:', err);
    }
  };

  const logMortality = async (batchId: string, quantity: number, reason: string, date: string) => {
    try {
      const { data: batch } = await supabase
        .from('batches')
        .select('current_quantity')
        .eq('id', batchId)
        .single();

      if (!batch) return;

      const actualQty = Math.min(batch.current_quantity, quantity);
      const newCurrentQty = batch.current_quantity - actualQty;

      const newLog = {
        id: `m-${Date.now()}`,
        batch_id: batchId,
        date,
        quantity: actualQty,
        reason
      };

      const [batchRes, mortRes] = await Promise.all([
        supabase
          .from('batches')
          .update({ current_quantity: newCurrentQty })
          .eq('id', batchId),
        supabase.from('mortality_logs').insert(newLog)
      ]);

      if (batchRes.error) throw batchRes.error;
      if (mortRes.error) throw mortRes.error;
      setBatches(prev => prev.map(b => {
        if (b.id === batchId) {
          return {
            ...b,
            currentQuantity: newCurrentQty,
            mortalityLogs: [...(b.mortalityLogs || []), newLog]
          };
        }
        return b;
      }));

      fetchAllData();
    } catch (err: any) {
      console.error('Failed to log mortality:', err);
      alert(`Error logging mortality: ${err.message || err}`);
    }
  };

  const updateMortalityLog = async (id: string, batchId: string, oldQty: number, newQty: number, reason: string, date: string) => {
    try {
      const { data: batch } = await supabase
        .from('batches')
        .select('current_quantity')
        .eq('id', batchId)
        .single();

      if (!batch) return;

      const diff = newQty - oldQty;
      const updatedCurrentQty = Math.max(0, batch.current_quantity - diff);

      await Promise.all([
        supabase
          .from('batches')
          .update({ current_quantity: updatedCurrentQty })
          .eq('id', batchId),
        supabase
          .from('mortality_logs')
          .update({ quantity: newQty, reason, date })
          .eq('id', id)
      ]);

      fetchAllData();
    } catch (err) {
      console.error('Failed to update mortality log:', err);
    }
  };

  const deleteMortalityLog = async (id: string, batchId: string, qty: number) => {
    try {
      const { data: batch } = await supabase
        .from('batches')
        .select('current_quantity')
        .eq('id', batchId)
        .single();

      if (batch) {
        await supabase
          .from('batches')
          .update({ current_quantity: batch.current_quantity + qty })
          .eq('id', batchId);
      }

      await supabase.from('mortality_logs').delete().eq('id', id);
      fetchAllData();
    } catch (err) {
      console.error('Failed to delete mortality log:', err);
    }
  };

  const deleteBatch = async (batchId: string) => {
    try {
      // Step 1: Get medical record IDs for this batch so we can delete their linked expenses
      const { data: medRecords } = await supabase
        .from('medical_records')
        .select('id')
        .eq('batch_id', batchId);

      // Step 2: Delete expenses auto-linked to medical records
      if (medRecords && medRecords.length > 0) {
        const medIds = medRecords.map((m: any) => m.id);
        await supabase
          .from('expenses')
          .delete()
          .in('reference_id', medIds)
          .eq('is_auto_generated', true);
      }

      // Step 3: Delete medical records for this batch
      await supabase.from('medical_records').delete().eq('batch_id', batchId);

      // Step 4: Delete vaccine schedules for this batch
      await supabase.from('vaccine_schedules').delete().eq('batch_id', batchId);

      // Step 5: Delete feed consumptions for this batch
      await supabase.from('feed_consumptions').delete().eq('batch_id', batchId);

      // Step 6: Delete mortality logs for this batch
      await supabase.from('mortality_logs').delete().eq('batch_id', batchId);

      // Step 7: Delete the auto-generated batch purchase expense
      await supabase
        .from('expenses')
        .delete()
        .eq('reference_id', batchId)
        .eq('is_auto_generated', true);

      // Step 8: Null out batch_id on any sales (preserve financial history)
      await supabase
        .from('sales')
        .update({ batch_id: null })
        .eq('batch_id', batchId);

      // Step 9: Finally delete the batch itself
      const { error } = await supabase.from('batches').delete().eq('id', batchId);
      if (error) throw error;

    } catch (err: any) {
      console.error('Failed to delete batch:', err);
      alert(`Delete failed: ${err?.message ?? 'Unknown error. Check console for details.'}`);
    }
  };


  const addFeedPurchase = async (purchase: Omit<FeedPurchase, 'id'>) => {
    const id = `fp-${Date.now()}`;
    const newPurchase = {
      id,
      date: purchase.date,
      feed_type: purchase.feedType,
      quantity_kg: purchase.quantityKg,
      cost: purchase.cost,
      vendor: purchase.vendor
    };

    const newExpense = {
      id: `exp-${Date.now()}`,
      category: 'Feed',
      date: purchase.date,
      description: `Feed Purchase: ${purchase.feedType} (${purchase.quantityKg} kg) from ${purchase.vendor}`,
      amount: purchase.cost,
      is_auto_generated: true,
      reference_id: id
    };

    await Promise.all([
      supabase.from('feed_purchases').insert(newPurchase),
      supabase.from('expenses').insert(newExpense)
    ]);
  };

  const addFeedConsumption = async (consumption: Omit<FeedConsumption, 'id'>) => {
    const id = `fc-${Date.now()}`;
    const newConsumption = {
      id,
      date: consumption.date,
      feed_type: consumption.feedType,
      batch_id: consumption.batchId,
      quantity_kg: consumption.quantityKg
    };
    await supabase.from('feed_consumptions').insert(newConsumption);
  };

  const getFeedStock = (type: FeedType): number => {
    const totalPurchased = feedPurchases
      .filter(p => p.feedType === type)
      .reduce((sum, p) => sum + p.quantityKg, 0);

    const totalConsumed = feedConsumption
      .filter(c => c.feedType === type)
      .reduce((sum, c) => sum + c.quantityKg, 0);

    return Math.max(0, totalPurchased - totalConsumed);
  };

  // 3. Health & Vaccination
  const addVaccineSchedule = async (schedule: Omit<VaccineSchedule, 'id' | 'status'>) => {
    const newSchedule = {
      id: `v-${Date.now()}`,
      vaccine_name: schedule.vaccineName,
      batch_id: schedule.batchId,
      scheduled_date: schedule.scheduledDate,
      status: 'Pending'
    };
    await supabase.from('vaccine_schedules').insert(newSchedule);
  };

  const updateVaccineStatus = async (id: string, status: VaccineStatus) => {
    await supabase
      .from('vaccine_schedules')
      .update({ status })
      .eq('id', id);
  };

  const deleteVaccineSchedule = async (id: string) => {
    try {
      await supabase.from('vaccine_schedules').delete().eq('id', id);
    } catch (err) {
      console.error('Failed to delete vaccine schedule:', err);
    }
  };

  const addMedicalRecord = async (record: Omit<MedicalRecord, 'id'>) => {
    const id = `mr-${Date.now()}`;
    const newRecord = {
      id,
      date: record.date,
      batch_id: record.batchId,
      disease: record.disease,
      medicine: record.medicine,
      dosage: record.dosage,
      cost: record.cost
    };

    const operations: any[] = [supabase.from('medical_records').insert(newRecord)];

    if (record.cost > 0) {
      const newExpense = {
        id: `exp-${Date.now()}`,
        category: 'Medicine',
        date: record.date,
        description: `Medical Treatment: Batch ${record.batchId} treated for ${record.disease} (${record.medicine})`,
        amount: record.cost,
        is_auto_generated: true,
        reference_id: id
      };
      operations.push(supabase.from('expenses').insert(newExpense));
    }

    await Promise.all(operations);
  };

  // 4. Egg Production
  const addEggCollection = async (collection: EggCollection) => {
    const existing = eggCollections.find(c => c.date === collection.date);
    
    let finalCollected = collection.collectedQty;
    let finalDamaged = collection.damagedQty;
    let finalNet = collection.netQty;

    if (existing) {
      finalCollected += existing.collectedQty;
      finalDamaged += existing.damagedQty;
      finalNet += existing.netQty;
    }

    const newCollection = {
      date: collection.date,
      collected_qty: finalCollected,
      damaged_qty: finalDamaged,
      net_qty: finalNet
    };
    
    const { error } = await supabase.from('egg_collections').upsert(newCollection);
    
    if (!error) {
      const finalEggCollection: EggCollection = {
        date: collection.date,
        collectedQty: finalCollected,
        damagedQty: finalDamaged,
        netQty: finalNet
      };

      setEggCollections(prev => {
        if (existing) {
          return prev.map(c => c.date === collection.date ? finalEggCollection : c);
        } else {
          const newList = [finalEggCollection, ...prev];
          return newList.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
        }
      });
    } else {
      console.error('Failed to add egg collection:', error);
    }
  };

  const deleteEggCollection = async (date: string) => {
    try {
      const { error } = await supabase.from('egg_collections').delete().eq('date', date);
      if (!error) {
        setEggCollections(prev => prev.filter(c => c.date !== date));
      }
    } catch (err) {
      console.error('Failed to delete egg collection:', err);
    }
  };

  const addEggSale = async (saleData: Omit<Sale, 'id' | 'invoiceId' | 'type' | 'batchId'>) => {
    const saleId = `s-${Date.now()}`;
    const invoiceNum = `INV-${new Date().getFullYear()}-${Math.floor(1000 + Math.random() * 9000)}`;
    
    const subtotal = saleData.totalAmount;
    const transportAmt = saleData.transportCharges || 0;
    const otherAmt = saleData.otherCharges || 0;
    const computedTotal = subtotal + transportAmt + otherAmt;
    const finalPaid = saleData.amountPaid ?? computedTotal;

    const detailsPayload = JSON.stringify({
      remarks: saleData.details || '',
      transport: transportAmt,
      other: otherAmt,
      oldBalance: saleData.oldBalance || 0,
      extraList: saleData.extraChargesList || [],
      updatedAt: new Date().toISOString()
    });

    const newSale = {
      id: saleId,
      invoice_id: invoiceNum,
      type: 'Egg',
      date: saleData.date,
      customer_name: saleData.customerName,
      customer_contact: saleData.customerContact,
      quantity: saleData.quantity,
      unit_price: saleData.unitPrice,
      total_amount: computedTotal,
      amount_paid: finalPaid,
      details: detailsPayload
    };
    
    try {
      const { error: saleErr } = await supabase.from('sales').insert(newSale);
      if (saleErr) {
        if (saleErr.code === '42703' || saleErr.message?.includes('amount_paid')) {
          console.warn("Supabase schema missing amount_paid column for egg sale. Retrying with localStorage fallback.");
          
          const localPayments = JSON.parse(localStorage.getItem('aksha_invoice_payments') || '{}');
          localPayments[saleId] = finalPaid;
          localStorage.setItem('aksha_invoice_payments', JSON.stringify(localPayments));

          if (finalPaid >= computedTotal) {
            const paidIds = JSON.parse(localStorage.getItem('aksha_paid_invoices') || '[]');
            if (!paidIds.includes(saleId)) {
              paidIds.push(saleId);
              localStorage.setItem('aksha_paid_invoices', JSON.stringify(paidIds));
            }
          }
          
          const retrySale: any = { ...newSale };
          delete retrySale.amount_paid;
          const { error: retryErr } = await supabase.from('sales').insert(retrySale);
          if (retryErr) throw retryErr;
        } else {
          throw saleErr;
        }
      }
    } catch (err: any) {
      console.error('Failed to add egg sale:', err);
      alert(`Error completing egg sale: ${err.message || err}`);
    }
  };

  const deleteSale = async (saleId: string) => {
    try {
      const sale = sales.find(s => s.id === saleId);
      if (!sale) return;

      const operations: any[] = [supabase.from('sales').delete().eq('id', saleId)];

      if (sale.type === 'Bird' && sale.batchId) {
        const { data: batch } = await supabase
          .from('batches')
          .select('current_quantity')
          .eq('id', sale.batchId)
          .single();

        if (batch) {
          const newQty = batch.current_quantity + sale.quantity;
          operations.push(
            supabase
              .from('batches')
              .update({ current_quantity: newQty, status: 'Active' })
              .eq('id', sale.batchId)
          );
        }
      }

      await Promise.all(operations);
    } catch (err) {
      console.error('Failed to delete sale:', err);
    }
  };

  // 5. Expense Management
  const addExpense = async (expense: Omit<Expense, 'id' | 'isAutoGenerated'>) => {
    const newExpense = {
      id: `exp-${Date.now()}`,
      category: expense.category,
      date: expense.date,
      description: expense.description,
      amount: expense.amount,
      is_auto_generated: false
    };
    await supabase.from('expenses').insert(newExpense);
  };

  const deleteExpense = async (id: string) => {
    try {
      const { data: expense } = await supabase
        .from('expenses')
        .select('*')
        .eq('id', id)
        .single();

      if (!expense) return;

      await supabase.from('expenses').delete().eq('id', id);

      if (expense.is_auto_generated && expense.reference_id) {
        if (expense.category === 'Feed') {
          await supabase.from('feed_purchases').delete().eq('id', expense.reference_id);
        } else if (expense.category === 'Medicine') {
          await supabase.from('medical_records').delete().eq('id', expense.reference_id);
        }
      }
    } catch (err) {
      console.error('Failed to delete expense:', err);
    }
  };

  const updateBatch = async (batchId: string, updated: Omit<BirdBatch, 'id' | 'mortalityLogs'>) => {
    try {
      const cost = updated.type === 'Broiler' && updated.initialQuantityKg && updated.purchasePricePerKg
        ? updated.initialQuantityKg * updated.purchasePricePerKg
        : updated.initialQuantity * updated.purchasePrice;

      const updatedBatch: any = {
        type: updated.type,
        arrival_date: updated.arrivalDate,
        initial_quantity: updated.initialQuantity,
        current_quantity: updated.currentQuantity,
        purchase_price: updated.purchasePrice,
        status: updated.status,
        initial_quantity_kg: updated.type === 'Broiler' ? updated.initialQuantityKg : null,
        purchase_price_per_kg: updated.type === 'Broiler' ? updated.purchasePricePerKg : null
      };

      const { error: batchErr } = await supabase
        .from('batches')
        .update(updatedBatch)
        .eq('id', batchId);

      if (batchErr) {
        if (batchErr.code === 'PGRST204' || batchErr.message?.includes('initial_quantity_kg') || batchErr.message?.includes('schema cache')) {
          console.warn("Supabase schema cache missing initial_quantity_kg columns. Retrying batch update without them.");
          alert("Notice: Broiler weight-based columns do not exist in your Supabase database. The batch will be updated as a standard bird batch. Please run the SQL migration at the bottom of schema.sql in your Supabase SQL Editor.");
          
          delete updatedBatch.initial_quantity_kg;
          delete updatedBatch.purchase_price_per_kg;

          const { error: retryErr } = await supabase
            .from('batches')
            .update(updatedBatch)
            .eq('id', batchId);
          if (retryErr) throw retryErr;
        } else {
          throw batchErr;
        }
      }

      const { error: expErr } = await supabase
        .from('expenses')
        .update({
          date: updated.arrivalDate,
          description: `Bird Batch Purchase: ${updated.type} - ${updated.initialQuantity} birds (ID: ${batchId})`,
          amount: cost
        })
        .eq('reference_id', batchId)
        .eq('is_auto_generated', true);
      
      if (expErr) throw expErr;

      fetchAllData();
    } catch (err: any) {
      console.error('Failed to update batch:', err);
      alert(`Error updating batch: ${err.message || err}`);
    }
  };

  const updateFeedPurchase = async (purchaseId: string, updated: Omit<FeedPurchase, 'id'>) => {
    try {
      const updatedPurchase = {
        date: updated.date,
        feed_type: updated.feedType,
        quantity_kg: updated.quantityKg,
        cost: updated.cost,
        vendor: updated.vendor
      };
      await Promise.all([
        supabase.from('feed_purchases').update(updatedPurchase).eq('id', purchaseId),
        supabase
          .from('expenses')
          .update({
            date: updated.date,
            description: `Feed Purchase: ${updated.feedType} (${updated.quantityKg} kg) from ${updated.vendor}`,
            amount: updated.cost
          })
          .eq('reference_id', purchaseId)
          .eq('is_auto_generated', true)
      ]);
    } catch (err) {
      console.error('Failed to update feed purchase:', err);
    }
  };

  const deleteFeedPurchase = async (purchaseId: string) => {
    try {
      await Promise.all([
        supabase.from('feed_purchases').delete().eq('id', purchaseId),
        supabase
          .from('expenses')
          .delete()
          .eq('reference_id', purchaseId)
          .eq('is_auto_generated', true)
      ]);
    } catch (err) {
      console.error('Failed to delete feed purchase:', err);
    }
  };

  const updateFeedConsumption = async (consumptionId: string, updated: Omit<FeedConsumption, 'id'>) => {
    try {
      await supabase
        .from('feed_consumptions')
        .update({
          date: updated.date,
          feed_type: updated.feedType,
          batch_id: updated.batchId,
          quantity_kg: updated.quantityKg
        })
        .eq('id', consumptionId);
    } catch (err) {
      console.error('Failed to update feed consumption:', err);
    }
  };

  const updateVaccineSchedule = async (id: string, updated: Omit<VaccineSchedule, 'id'>) => {
    try {
      await supabase
        .from('vaccine_schedules')
        .update({
          vaccine_name: updated.vaccineName,
          batch_id: updated.batchId,
          scheduled_date: updated.scheduledDate,
          status: updated.status
         })
        .eq('id', id);
    } catch (err) {
      console.error('Failed to update vaccine schedule:', err);
    }
  };

  const updateMedicalRecord = async (recordId: string, updated: Omit<MedicalRecord, 'id'>) => {
    try {
      const updatedRecord = {
        date: updated.date,
        batch_id: updated.batchId,
        disease: updated.disease,
        medicine: updated.medicine,
        dosage: updated.dosage,
        cost: updated.cost
      };
      
      await supabase.from('medical_records').update(updatedRecord).eq('id', recordId);
      
      if (updated.cost > 0) {
        const newExpense = {
          category: 'Medicine',
          date: updated.date,
          description: `Medical Treatment: Batch ${updated.batchId} treated for ${updated.disease} (${updated.medicine})`,
          amount: updated.cost,
          is_auto_generated: true,
          reference_id: recordId
        };
        
        const { data: existingExp } = await supabase
          .from('expenses')
          .select('id')
          .eq('reference_id', recordId)
          .eq('is_auto_generated', true)
          .maybeSingle();
          
        if (existingExp) {
          await supabase
            .from('expenses')
            .update(newExpense)
            .eq('id', existingExp.id);
        } else {
          await supabase
            .from('expenses')
            .insert({
              id: `exp-${Date.now()}`,
              ...newExpense
            });
        }
      } else {
        await supabase
          .from('expenses')
          .delete()
          .eq('reference_id', recordId)
          .eq('is_auto_generated', true);
      }
    } catch (err) {
      console.error('Failed to update medical record:', err);
    }
  };

  const deleteMedicalRecord = async (id: string) => {
    try {
      await Promise.all([
        supabase.from('medical_records').delete().eq('id', id),
        supabase.from('expenses').delete().eq('reference_id', id).eq('is_auto_generated', true)
      ]);
      fetchAllData();
    } catch (err) {
      console.error('Failed to delete medical record:', err);
    }
  };

  const updateEggCollection = async (originalDate: string, updated: EggCollection) => {
    try {
      if (originalDate !== updated.date) {
        await supabase.from('egg_collections').delete().eq('date', originalDate);
      }
      const { error } = await supabase.from('egg_collections').upsert({
        date: updated.date,
        collected_qty: updated.collectedQty,
        damaged_qty: updated.damagedQty,
        net_qty: updated.netQty
      });
      if (!error) {
        setEggCollections(prev => {
          let newList = prev.filter(c => c.date !== originalDate);
          newList = newList.filter(c => c.date !== updated.date);
          newList.push(updated);
          return newList.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
        });
      }
    } catch (err) {
      console.error('Failed to update egg collection:', err);
    }
  };

  const updateSale = async (saleId: string, updated: Omit<Sale, 'id' | 'invoiceId'>) => {
    try {
      const sale = sales.find(s => s.id === saleId);
      if (!sale) return;
      
      const operations: any[] = [];
      
      const subtotal = updated.totalAmount;
      const transportAmt = updated.transportCharges || 0;
      const otherAmt = updated.otherCharges || 0;
      const computedTotal = subtotal + transportAmt + otherAmt;
      const finalPaid = updated.amountPaid ?? computedTotal;

      const detailsPayload = JSON.stringify({
        remarks: updated.details || '',
        transport: transportAmt,
        other: otherAmt,
        oldBalance: updated.oldBalance || 0,
        extraList: updated.extraChargesList || [],
        updatedAt: new Date().toISOString()
      });

      const updatedSale: any = {
        type: updated.type,
        date: updated.date,
        customer_name: updated.customerName,
        customer_contact: updated.customerContact,
        quantity: updated.quantity,
        unit_price: updated.unitPrice,
        total_amount: computedTotal,
        amount_paid: finalPaid,
        batch_id: updated.batchId || null,
        details: detailsPayload,
        weight_kg: updated.weightKg || null,
        price_per_kg: updated.pricePerKg || null
      };

      const performSalesUpdate = async () => {
        try {
          console.log('[updateSale] Sending to Supabase:', saleId, updatedSale);
          const { error: updateErr } = await supabase.from('sales').update(updatedSale).eq('id', saleId);
          console.log('[updateSale] Supabase response error:', updateErr);
          if (updateErr) {
            let currentErr = updateErr;
            
            // Handle amount_paid missing
            if (currentErr.code === '42703' || currentErr.message?.includes('amount_paid')) {
              console.warn("Supabase schema missing amount_paid column. Saving to localStorage and retrying.");
              
              const localPayments = JSON.parse(localStorage.getItem('aksha_invoice_payments') || '{}');
              localPayments[saleId] = finalPaid;
              localStorage.setItem('aksha_invoice_payments', JSON.stringify(localPayments));

              const paidIds = JSON.parse(localStorage.getItem('aksha_paid_invoices') || '[]');
              const paidSet = new Set(paidIds);
              if (finalPaid >= computedTotal) {
                paidSet.add(saleId);
              } else {
                paidSet.delete(saleId);
              }
              localStorage.setItem('aksha_paid_invoices', JSON.stringify([...paidSet]));

              delete updatedSale.amount_paid;
              const { error: retryErr } = await supabase.from('sales').update(updatedSale).eq('id', saleId);
              if (retryErr) currentErr = retryErr;
              else currentErr = null as any;
            }

            // Handle weight_kg / price_per_kg missing
            if (currentErr && (currentErr.code === 'PGRST204' || currentErr.message?.includes('weight_kg') || currentErr.message?.includes('schema cache') || currentErr.message?.includes('price_per_kg'))) {
              console.warn("Supabase schema cache missing weight_kg/price_per_kg columns. Retrying without weight columns.");
              delete updatedSale.weight_kg;
              delete updatedSale.price_per_kg;
              updatedSale.total_amount = updated.quantity * updated.unitPrice;
              
              const { error: retryErr2 } = await supabase.from('sales').update(updatedSale).eq('id', saleId);
              if (retryErr2) throw retryErr2;
            } else if (currentErr) {
              throw currentErr;
            }
          }
        } catch (err) {
          console.error("Sales table update failed:", err);
          throw err;
        }
      };

      operations.push(performSalesUpdate());
      
      if (sale.type === 'Bird' && sale.batchId) {
        const { data: oldBatch } = await supabase
          .from('batches')
          .select('current_quantity')
          .eq('id', sale.batchId)
          .single();
          
        if (oldBatch) {
          const revertedQty = oldBatch.current_quantity + sale.quantity;
          
          if (updated.type === 'Bird' && updated.batchId) {
            if (updated.batchId === sale.batchId) {
              const finalQty = revertedQty - updated.quantity;
              operations.push(
                supabase.from('batches').update({
                  current_quantity: Math.max(0, finalQty),
                  status: finalQty <= 0 ? 'Sold' : 'Active'
                }).eq('id', sale.batchId)
              );
            } else {
              operations.push(
                supabase.from('batches').update({
                  current_quantity: revertedQty,
                  status: revertedQty <= 0 ? 'Sold' : 'Active'
                }).eq('id', sale.batchId)
              );
              
              const { data: newBatch } = await supabase
                .from('batches')
                .select('current_quantity')
                .eq('id', updated.batchId)
                .single();
                
              if (newBatch) {
                const finalNewQty = Math.max(0, newBatch.current_quantity - updated.quantity);
                operations.push(
                  supabase.from('batches').update({
                    current_quantity: finalNewQty,
                    status: finalNewQty <= 0 ? 'Sold' : 'Active'
                  }).eq('id', updated.batchId)
                );
              }
            }
          } else {
            operations.push(
              supabase.from('batches').update({
                current_quantity: revertedQty,
                status: revertedQty <= 0 ? 'Sold' : 'Active'
              }).eq('id', sale.batchId)
            );
          }
        }
      } else if (updated.type === 'Bird' && updated.batchId) {
        const { data: newBatch } = await supabase
          .from('batches')
          .select('current_quantity')
          .eq('id', updated.batchId)
          .single();
          
        if (newBatch) {
          const finalNewQty = Math.max(0, newBatch.current_quantity - updated.quantity);
          operations.push(
            supabase.from('batches').update({
              current_quantity: finalNewQty,
              status: finalNewQty <= 0 ? 'Sold' : 'Active'
            }).eq('id', updated.batchId)
          );
        }
      }
      
      await Promise.all(operations);

      // Optimistic local state update — keeps UI in sync without a full page refresh
      setSales(prev => prev.map(s => {
        if (s.id !== saleId) return s;
        return {
          ...s,
          type: updated.type,
          date: updated.date,
          customerName: updated.customerName,
          customerContact: updated.customerContact,
          quantity: updated.quantity,
          unitPrice: updated.unitPrice,
          totalAmount: computedTotal,   // full total = subtotal + transport + other (matches DB)
          amountPaid: finalPaid,
          transportCharges: transportAmt,
          otherCharges: otherAmt,
          extraChargesList: updated.extraChargesList || [],
          oldBalance: updated.oldBalance || 0,
          details: updated.details || '',
          batchId: updated.batchId,
          weightKg: updated.weightKg,
          pricePerKg: updated.pricePerKg
        };
      }));
    } catch (err) {
      console.error('Failed to update sale:', err);
      throw err; // re-throw so callers can show user-facing errors
    }
  };

  const updateExpense = async (id: string, updated: Omit<Expense, 'id' | 'isAutoGenerated'>) => {
    try {
      const expense = expenses.find(e => e.id === id);
      if (!expense) return;
      
      await supabase
        .from('expenses')
        .update({
          category: updated.category,
          date: updated.date,
          description: updated.description,
          amount: updated.amount
        })
        .eq('id', id);
        
      if (expense.isAutoGenerated && expense.referenceId) {
        if (expense.category === 'Feed') {
          await supabase
            .from('feed_purchases')
            .update({
              date: updated.date,
              cost: updated.amount
             })
            .eq('id', expense.referenceId);
        } else if (expense.category === 'Medicine') {
          await supabase
            .from('medical_records')
            .update({
              date: updated.date,
              cost: updated.amount
            })
            .eq('id', expense.referenceId);
        }
      }
    } catch (err) {
      console.error('Failed to update expense:', err);
    }
  };

  // ----------------------------------------------------
  // EMPLOYEE PENDING SUBMISSION APPROVAL QUEUE
  // ----------------------------------------------------
  const [pendingSubmissions, setPendingSubmissions] = useState<PendingSubmission[]>(() => {
    try {
      const saved = localStorage.getItem('aksha_pending_submissions');
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  useEffect(() => {
    localStorage.setItem('aksha_pending_submissions', JSON.stringify(pendingSubmissions));
  }, [pendingSubmissions]);

  const submitForApproval = (type: PendingSubmissionType, data: any) => {
    const newSubmission: PendingSubmission = {
      id: `SUB-${Date.now()}-${Math.random().toString(36).substring(2, 6).toUpperCase()}`,
      type,
      submittedBy: currentUser?.username || 'employee',
      submittedAt: new Date().toISOString(),
      data,
      status: 'Pending'
    };
    setPendingSubmissions(prev => [newSubmission, ...prev]);
    return newSubmission;
  };

  const approveSubmission = async (submissionId: string) => {
    const sub = pendingSubmissions.find(s => s.id === submissionId);
    if (!sub || sub.status !== 'Pending') return;

    try {
      switch (sub.type) {
        case 'Mortality':
          logMortality(sub.data.batchId, Number(sub.data.quantity), sub.data.reason, sub.data.date);
          break;
        case 'EggCollection':
          addEggCollection(sub.data);
          break;
        case 'FeedConsumption':
          addFeedConsumption(sub.data);
          break;
        case 'FeedPurchase':
          addFeedPurchase(sub.data);
          break;
        case 'VaccineSchedule':
          addVaccineSchedule(sub.data);
          break;
        case 'VaccineStatusUpdate':
          await updateVaccineStatus(sub.data.vaccineId, sub.data.status);
          break;
        case 'MedicalRecord':
          addMedicalRecord(sub.data);
          break;
        case 'BirdBatch':
          addBatch(sub.data);
          break;
      }

      setPendingSubmissions(prev =>
        prev.map(s =>
          s.id === submissionId
            ? {
                ...s,
                status: 'Approved' as const,
                reviewedBy: currentUser?.username || 'admin',
                reviewedAt: new Date().toISOString()
              }
            : s
        )
      );
    } catch (err) {
      console.error('Failed to approve submission:', err);
      throw err;
    }
  };

  const rejectSubmission = (submissionId: string, reason?: string) => {
    setPendingSubmissions(prev =>
      prev.map(s =>
        s.id === submissionId
          ? {
              ...s,
              status: 'Rejected' as const,
              reviewedBy: currentUser?.username || 'admin',
              reviewedAt: new Date().toISOString(),
              rejectionReason: reason || 'Declined by Administrator'
            }
          : s
      )
    );
  };

  const deletePendingSubmission = (submissionId: string) => {
    setPendingSubmissions(prev => prev.filter(s => s.id !== submissionId));
  };

  return (
    <FarmContext.Provider
      value={{
        currentUser,
        login,
        logout,
        batches,
        addBatch,
        deleteBatch,
        sellBatch,
        logMortality,
        updateMortalityLog,
        deleteMortalityLog,
        feedPurchases,
        addFeedPurchase,
        feedConsumption,
        addFeedConsumption,
        vaccines,
        addVaccineSchedule,
        updateVaccineStatus,
        deleteVaccineSchedule,
        medicalRecords,
        addMedicalRecord,
        deleteMedicalRecord,
        eggCollections,
        addEggCollection,
        deleteEggCollection,
        sales,
        addEggSale,
        deleteSale,
        expenses,
        addExpense,
        deleteExpense,
        updateBatch,
        updateFeedPurchase,
        deleteFeedPurchase,
        updateFeedConsumption,
        updateVaccineSchedule,
        updateMedicalRecord,
        updateEggCollection,
        updateSale,
        updateExpense,
        getFeedStock,
        usersList,
        registerUser,
        approveUser,
        updateUserRole,
        updateUserProfile,
        resetUserPassword,
        verifyAndResetPassword,
        deleteUser,
        pendingSubmissions,
        submitForApproval,
        approveSubmission,
        rejectSubmission,
        deletePendingSubmission,
        isLoading
      }}
    >
      {children}
    </FarmContext.Provider>
  );
};

export const useFarm = () => {
  const context = useContext(FarmContext);
  if (!context) {
    throw new Error('useFarm must be used within a FarmProvider');
  }
  return context;
};

